# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

mkdocs:
  configuration: mkdocs.yaml

# Optionally set the version of Python and requirements required to build your docs
python:
#  version: "3.9"
  install:
    - requirements: docs/requirements.txt